// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAyJ5yZlBA4j_52Lxkd-lJjzBzMavH-mc',
    appId: '1:232493173990:web:284e50f72218066c217f27',
    messagingSenderId: '232493173990',
    projectId: 'swynex',
    authDomain: 'swynex.firebaseapp.com',
    storageBucket: 'swynex.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADiS4CmPM6hcOQ54GkEIXNGdr-35o7094',
    appId: '1:232493173990:android:1a2ce2448457a4d5217f27',
    messagingSenderId: '232493173990',
    projectId: 'swynex',
    storageBucket: 'swynex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4pR3-aWp0chKT9_kASiVnQSWKlCK4AiA',
    appId: '1:232493173990:ios:db89962716485d53217f27',
    messagingSenderId: '232493173990',
    projectId: 'swynex',
    storageBucket: 'swynex.firebasestorage.app',
    iosBundleId: 'com.example.pigLifecycleCrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4pR3-aWp0chKT9_kASiVnQSWKlCK4AiA',
    appId: '1:232493173990:ios:db89962716485d53217f27',
    messagingSenderId: '232493173990',
    projectId: 'swynex',
    storageBucket: 'swynex.firebasestorage.app',
    iosBundleId: 'com.example.pigLifecycleCrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAyJ5yZlBA4j_52Lxkd-lJjzBzMavH-mc',
    appId: '1:232493173990:web:c5089dfd7c810675217f27',
    messagingSenderId: '232493173990',
    projectId: 'swynex',
    authDomain: 'swynex.firebaseapp.com',
    storageBucket: 'swynex.firebasestorage.app',
  );
}
